In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
# laod Excel data
df = pd.read_excel('Netflix_Unclean_Project.xlsx')

In [3]:
# check
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20

In [4]:
df.tail()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [5]:
# Initial Data Exploration
df.shape

(1013, 20)

In [6]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Title', 'Content_Type', 'Genre',
       'Country', 'Subscription_Plan', 'Device', 'Payment_Method',
       'Account_Status', 'Join_Date', 'Last_Watch_Date', 'Watch_Hours',
       'Monthly_Fee', 'Movies_Watched', 'Episodes_Watched', 'Avg_Rating',
       'Monthly_Sessions', 'Download_Count'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1013 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1013 non-null   object
 1   Customer_Name      1013 non-null   object
 2   Age                1013 non-null   int64
 3   Title              1013 non-null   object
 4   Content_Type       1013 non-null   object
 5   Genre              1010 non-null   object
 6   Country            1013 non-null   object
 7   Subscription_Plan  1013 non-null   object
 8   Device             1009 non-null   object
 9   Payment_Method     1008 non-null   object
 10  Account_Status     1013 non-null   object
 11  Join_Date          1013 non-null   datetime64[ns]
 12  Last_Watch_Date    1013 non-null   datetime64[ns]
 13  Watch_Hours        1013 non-null   float64
 14  Monthly_Fee        1013 non-null   int64
 15  Movies_Watched     1013 non-null   int64
 16  Episodes_Watched   1013 non-null   int64
 17  Avg_Rating         1013 non-null   float64
 18  Monthly_Sessions   1013 non-null   int64
 19  Download_Count     1013 non-null   int64
dtypes: datetime64[ns](2), float64(2), int64(6), object(10)
memory usage: 158.4+ KB

In [8]:
# Statistical Summary
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1013.000000,1013,1013,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000
mean,42.063179,2023-12-16 10:21:12.260612096,2024-11-27 19:59:45.784797696,42.417473,436.222113,18.187562,59.834156,3.752419,16.686081,12.472853
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-08 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,31.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-29 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-13 00:00:00,2025-11-14 00:00:00,58.100000,649.000000,27.000000,91.000000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.245811,NaN,NaN,23.988529,214.348252,10.123758,34.895300,0.722812,8.290083,7.577303

In [9]:
# Missing Values
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                3
Country              0
Subscription_Plan    0
Device               4
Payment_Method       5
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [10]:
# Duplicate Records
df.duplicated().sum()

5

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()   #remove duplicates

0

In [13]:
# Dirty value - N/A,NULL,blank,spaces
df.replace(
    ['N/A','NULL','',' '],np.nan,inplace=True
)

In [14]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                4
Country              1
Subscription_Plan    0
Device               4
Payment_Method       7
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [15]:
df

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [16]:
# Extra Spaces Remove

df=df.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)

In [17]:
# Standardize Text
df["Country"] = df["Country"].str.title()
df["Genre"] = df["Genre"].str.title()

df["Subscription_Plan"] = (df["Subscription_Plan"].str.title())

df["Account_Status"] = (df["Account_Status"].str.title()
)

In [18]:
df['Country'].value_counts()

Country
Spain             109
United States     107
Germany           104
Canada            103
United Kingdom    102
Japan             100
France             98
India              97
South Korea        96
Australia          91
Name: count, dtype: int64

In [19]:
# Numeric Columns
numeric_cols = ['Age', 'Watch_Hours', 
                'Monthly_Fee', 'Movies_Watched' , 
                'Episodes_Watched', 'Avg_Rating',
                'Monthly_Sessions', 'Download_Count']

In [20]:
for col in numeric_cols: 
    df[col]=pd.to_numeric(df[col],errors='coerce')

In [21]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1008.000000,1008,1008,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000
mean,42.097222,2023-12-15 20:42:51.428571392,2024-11-28 00:20:00.000000256,42.449107,435.960317,18.226190,59.766865,3.751984,16.690476,12.448413
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-07 18:00:00,2023-12-25 12:00:00,25.650000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,54.000000,2024-12-13 00:00:00,2025-11-14 06:00:00,58.100000,649.000000,27.000000,90.250000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.258334,NaN,NaN,24.016448,214.461100,10.099231,34.916046,0.724172,8.287380,7.559714

In [22]:
df = df[(df['Age']>=18)&(df['Age']<=100)]

In [23]:
df['Age'].describe()

count    1003.000000
mean       41.973081
std        13.811906
min        18.000000
25%        30.000000
50%        43.000000
75%        53.500000
max        65.000000
Name: Age, dtype: float64

In [24]:
# Negative Values
df=df[df['Watch_Hours']>=0]
df=df[df['Monthly_Fee']>=0]

In [25]:
# Data Cleaning
df['Join_Date']=pd.to_datetime(df['Join_Date'],errors='coerce')
df['Last_Watch_Date']=pd.to_datetime(df['Last_Watch_Date'],errors='coerce')

In [26]:
# Missing values handle
df['Age']=df['Age'].fillna (
    df['Age'].mean()
)
df['Watch_Hours']=df['Watch_Hours'].fillna(
    df['Watch_Hours'].mean()
)
df['Monthly_Fee']=df['Monthly_Fee'].fillna(
    df['Monthly_Fee'].mean()
)

In [27]:
df['Payment_Method']=df['Payment_Method'].fillna("Unknown")
df['Device']=df['Device'].fillna("Unknown")
df['Genre']=df['Genre'].fillna("Unknown")

In [28]:
# Feature Engineering

#Customer Revenue
df['Customer_Revenue']=(df['Monthly_Fee']*df['Monthly_Sessions'])

In [29]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3,7139
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19,3278
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3,3874
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9,17523
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20,9735

In [30]:
# Engagement Score
df['Engagement_Score'] = (df['Watch_Hours']+df['Monthly_Sessions']+df['Download_Count'])

In [31]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,2024-12-21,28.0,649,5,97,3.6,11,3,7139,42.0
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,2024-08-14,0.0,149,5,84,4.5,22,19,3278,41.0
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,2025-10-31,28.9,149,16,106,3.8,26,3,3874,57.9
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,2023-06-18,27.6,649,10,24,2.6,27,9,17523,63.6
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,2025-06-09,32.0,649,10,78,3.2,15,20,9735,67.0

In [32]:
# Watch Category
bins=[0,20,50,100,np.inf]
label=['Low','Medium','High','Very High']
df['Watch_Category']=pd.cut(df['Watch_Hours'],bins=bins,labels=label)

In [33]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,28.0,649,5,97,3.6,11,3,7139,42.0,Medium
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,0.0,149,5,84,4.5,22,19,3278,41.0,NaN
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,28.9,149,16,106,3.8,26,3,3874,57.9,Medium
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,27.6,649,10,24,2.6,27,9,17523,63.6,Medium
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,32.0,649,10,78,3.2,15,20,9735,67.0,Medium

In [34]:
df['Watch_Category'].value_counts()

Watch_Category
Medium       449
High         357
Low          142
Very High     10
Name: count, dtype: int64

In [35]:
# Customer Age Group
bins=[17,25,35,50,100]
label=['18-25','26-35','36-50','51+']
df['Age_Group']=pd.cut(df['Age'],bins=bins,labels=label)

In [36]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,649,5,97,3.6,11,3,7139,42.0,Medium,18-25
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,149,5,84,4.5,22,19,3278,41.0,NaN,36-50
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,149,16,106,3.8,26,3,3874,57.9,Medium,36-50
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,649,10,24,2.6,27,9,17523,63.6,Medium,36-50
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,649,10,78,3.2,15,20,9735,67.0,Medium,51+

In [37]:
df['Age_Group'].value_counts()

Age_Group
51+      325
36-50    308
26-35    215
18-25    147
Name: count, dtype: int64

In [38]:
# Account Active Flag
df['Active_Falg']=np.where(df['Account_Status'] == 'Active',1,0)

In [39]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group,Active_Falg
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,5,97,3.6,11,3,7139,42.0,Medium,18-25,1
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,5,84,4.5,22,19,3278,41.0,NaN,36-50,1
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,16,106,3.8,26,3,3874,57.9,Medium,36-50,0
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,10,24,2.6,27,9,17523,63.6,Medium,36-50,1
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,10,78,3.2,15,20,9735,67.0,Medium,51+,1

In [40]:
# Final data quality check
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 995 entries, 0 to 1012
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        995 non-null    object
 1   Customer_Name      995 non-null    object
 2   Age                995 non-null    int64
 3   Title              995 non-null    object
 4   Content_Type       995 non-null    object
 5   Genre              995 non-null    object
 6   Country            994 non-null    object
 7   Subscription_Plan  995 non-null    object
 8   Device             995 non-null    object
 9   Payment_Method     995 non-null    object
 10  Account_Status     995 non-null    object
 11  Join_Date          995 non-null    datetime64[ns]
 12  Last_Watch_Date    995 non-null    datetime64[ns]
 13  Watch_Hours        995 non-null    float64
 14  Monthly_Fee        995 non-null    int64
 15  Movies_Watched     995 non-null    int64
 16  Episodes_Watched   995 non-null    int64
 17  Avg_Rating         995 non-null    float64
 18  Monthly_Sessions   995 non-null    int64
 19  Download_Count     995 non-null    int64
 20  Customer_Revenue   995 non-null    int64
 21  Engagement_Score   995 non-null    float64
 22  Watch_Category     958 non-null    category
 23  Age_Group          995 non-null    category
 24  Active_Falg        995 non-null    int32
dtypes: category(2), datetime64[ns](2), float64(3), int32(1), int64(7), object(10)
memory usage: 185.0+ KB

In [41]:
df.isnull().sum()

Customer_ID           0
Customer_Name         0
Age                   0
Title                 0
Content_Type          0
Genre                 0
Country               1
Subscription_Plan     0
Device                0
Payment_Method        0
Account_Status        0
Join_Date             0
Last_Watch_Date       0
Watch_Hours           0
Monthly_Fee           0
Movies_Watched        0
Episodes_Watched      0
Avg_Rating            0
Monthly_Sessions      0
Download_Count        0
Customer_Revenue      0
Engagement_Score      0
Watch_Category       37
Age_Group             0
Active_Falg           0
dtype: int64

In [42]:
df.duplicated().sum()

0

In [43]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Active_Falg
count,995.000000,995,995,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000
mean,41.920603,2023-12-16 04:27:44.321607936,2024-11-27 13:52:09.648241152,42.605126,438.396985,18.217085,59.514573,3.754573,16.701508,12.460302,7339.680402,71.766935,0.708543
min,18.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,0.000000,149.000000,1.000000,0.000000,2.500000,2.000000,0.000000,298.000000,11.000000,0.000000
25%,30.000000,2022-12-09 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000,2682.000000,51.200000,0.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-02 00:00:00,42.300000,499.000000,18.000000,58.000000,3.700000,17.000000,12.000000,5841.000000,71.700000,1.000000
75%,53.000000,2024-12-10 00:00:00,2025-11-12 00:00:00,58.100000,649.000000,27.000000,90.000000,4.400000,24.000000,19.000000,11477.000000,90.050000,1.000000
max,65.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000,19470.000000,167.300000,1.000000
std,13.797644,NaN,NaN,23.784772,209.136478,10.085605,34.855299,0.723983,8.280686,7.564557,5344.095657,26.202570,0.454662

In [44]:
df['Country'].fillna(df['Country'].mode()[0],inplace=True)
df['Watch_Category'].fillna(df['Watch_Category'].mode()[0],inplace=True)

C:\Users\SAPTACOM\AppData\Local\Temp\ipykernel_9964\299194288.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Country'].fillna(df['Country'].mode()[0],inplace=True)
C:\Users\SAPTACOM\AppData\Local\Temp\ipykernel_9964\299194288.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Watch_Category'].fillna(df['Watch_Category'].mode()[0],inplace=True)

In [45]:
df.isnull().sum()  # remove all null values

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                0
Country              0
Subscription_Plan    0
Device               0
Payment_Method       0
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
Customer_Revenue     0
Engagement_Score     0
Watch_Category       0
Age_Group            0
Active_Falg          0
dtype: int64

In [46]:
# Clean csv Export
df.to_csv('Netflix_Clean_Data.csv',index=False)

In [47]:
import os
os.getcwd()

'C:\\Users\\SAPTACOM\\DA_Project'

In [48]:
import os
os.chdir(r"E:\Ethans DA & DS\Project\DA_Project\Netflix Dummy Data\Netflix_Clean_Data")

In [49]:
print(os.getcwd())

E:\Ethans DA & DS\Project\DA_Project\Netflix Dummy Data\Netflix_Clean_Data

In [50]:
df.to_csv('Netflix_Clean_Data.csv',index=False)

In [51]:
# pdbc
!pip install pymysql
from sqlalchemy import create_engine
engine=create_engine('mysql+pymysql://root:dhanu%402005@localhost/netflix_db')

Requirement already satisfied: pymysql in c:\users\saptacom\anaconda3\lib\site-packages (1.2.3)

In [52]:
df.to_sql(
    'netflix_customers',
    con=engine,
    if_exists = 'replace',
    index = False
)

995